"""initial_schema

Revision ID: 08af52f689f2
Revises: 
Create Date: 2026-09-10 08:26:36.287367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08af52f689f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('processed_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_id'), 'manufacturers', ['id'], unique=False)
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=True)
    op.create_table('message_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('parent_user_message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_feedbacks_conversation_id'), 'message_feedbacks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_feedbacks_id'), 'message_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_message_feedbacks_message_id'), 'message_feedbacks', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_feedbacks_user_id'), 'message_feedbacks', ['user_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_domain'), 'sources', ['domain'], unique=False)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('car_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('body_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_models_body_type'), 'car_models', ['body_type'], unique=False)
    op.create_index(op.f('ix_car_models_id'), 'car_models', ['id'], unique=False)
    op.create_index(op.f('ix_car_models_name'), 'car_models', ['name'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_detail', sa.String(length=50), nullable=False),
    sa.Column('units', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('car_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('variant_name', sa.String(length=255), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('ex_showroom_price', sa.Float(), nullable=False),
    sa.Column('estimated_on_road_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('transmission', sa.String(length=50), nullable=False),
    sa.Column('engine_cc', sa.Integer(), nullable=True),
    sa.Column('cylinders', sa.Integer(), nullable=True),
    sa.Column('horsepower', sa.Float(), nullable=True),
    sa.Column('torque_nm', sa.Float(), nullable=True),
    sa.Column('mileage_city', sa.Float(), nullable=True),
    sa.Column('mileage_highway', sa.Float(), nullable=True),
    sa.Column('combined_mileage', sa.Float(), nullable=True),
    sa.Column('battery_capacity', sa.Float(), nullable=True),
    sa.Column('electric_range', sa.Float(), nullable=True),
    sa.Column('charging_time', sa.Float(), nullable=True),
    sa.Column('seating_capacity', sa.Integer(), nullable=False),
    sa.Column('airbags', sa.Integer(), nullable=False),
    sa.Column('safety_rating', sa.Float(), nullable=True),
    sa.Column('boot_space', sa.Integer(), nullable=True),
    sa.Column('ground_clearance', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('wheelbase', sa.Integer(), nullable=True),
    sa.Column('drive_type', sa.String(length=50), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('safety_features', sa.JSON(), nullable=True),
    sa.Column('infotainment_features', sa.JSON(), nullable=True),
    sa.Column('comfort_features', sa.JSON(), nullable=True),
    sa.Column('pros', sa.JSON(), nullable=True),
    sa.Column('cons', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['car_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_variants_airbags'), 'car_variants', ['airbags'], unique=False)
    op.create_index(op.f('ix_car_variants_combined_mileage'), 'car_variants', ['combined_mileage'], unique=False)
    op.create_index(op.f('ix_car_variants_ex_showroom_price'), 'car_variants', ['ex_showroom_price'], unique=False)
    op.create_index(op.f('ix_car_variants_fuel_type'), 'car_variants', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_car_variants_id'), 'car_variants', ['id'], unique=False)
    op.create_index(op.f('ix_car_variants_model_year'), 'car_variants', ['model_year'], unique=False)
    op.create_index(op.f('ix_car_variants_safety_rating'), 'car_variants', ['safety_rating'], unique=False)
    op.create_index(op.f('ix_car_variants_seating_capacity'), 'car_variants', ['seating_capacity'], unique=False)
    op.create_index(op.f('ix_car_variants_transmission'), 'car_variants', ['transmission'], unique=False)
    op.create_index(op.f('ix_car_variants_variant_name'), 'car_variants', ['variant_name'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('saved_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['car_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_cars_id'), 'saved_cars', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_cars_id'), table_name='saved_cars')
    op.drop_table('saved_cars')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_car_variants_variant_name'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_transmission'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_seating_capacity'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_safety_rating'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_model_year'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_id'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_fuel_type'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_ex_showroom_price'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_combined_mileage'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_airbags'), table_name='car_variants')
    op.drop_table('car_variants')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_car_models_name'), table_name='car_models')
    op.drop_index(op.f('ix_car_models_id'), table_name='car_models')
    op.drop_index(op.f('ix_car_models_body_type'), table_name='car_models')
    op.drop_table('car_models')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_domain'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_message_feedbacks_user_id'), table_name='message_feedbacks')
    op.drop_index(op.f('ix_message_feedbacks_message_id'), table_name='message_feedbacks')
    op.drop_index(op.f('ix_message_feedbacks_id'), table_name='message_feedbacks')
    op.drop_index(op.f('ix_message_feedbacks_conversation_id'), table_name='message_feedbacks')
    op.drop_table('message_feedbacks')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_id'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
